### ISSUE TITLE
[ASAN] heap-buffer-overflow in L1TrackerEtMissEmulatorProducer

### ISSUE THREAD

**Issue by aloeliger** [cms-l1t-offline/cmssw#1101]
#### What
Taken from https://github.com/cms-sw/cmssw/issues/41320

> ASAN reports in CMSSW_13_1_ASAN_X_2023-04-10-2300 workflow 23834.999 step 3
> 
> ```
> ==26001==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x625005383900 at pc 0x2b759174aeba bp 0x7ffef4608e10 sp 0x7ffef4608e08
> READ of size 2 at 0x625005383900 thread T0
>     #0 0x2b759174aeb9 in ap_fixed_base<20, 15, true, (ap_q_mode)4, (ap_o_mode)0, 0>::RType<10, 1, false>::mult ap_fixed_base<20, 15, true, (ap_q_mode)4, (ap_o_mode)0, 0>::operator*<10, 1, false, (ap_q_mode)4, (ap_o_mode)0, 0>(ap_fixed_base<10, 1, false, (ap_q_mode)4, (ap_o_mode)0, 0> const&) const (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/pluginL1TrackTriggerPlugins.so+0x18beb9)
>     #1 0x2b759175f2d7 in L1TrackerEtMissEmulatorProducer::produce(edm::Event&, edm::EventSetup const&) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/pluginL1TrackTriggerPlugins.so+0x1a02d7)
>     #2 0x2b7502de3807 in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so+0x7a7807)
>     #3 0x2b7502d795e0 in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so+0x73d5e0)
>     #4 0x2b7502b2005c in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so+0x4e405c)
>     #5 0x2b7502b425ca in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so+0x5065ca)
>     #6 0x2b75037f66cb in tbb::detail::d1::function_task<edm::WaitingTaskList::announce()::{lambda()#1}>::execute(tbb::detail::d1::execution_data&) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/libFWCoreConcurrency.so+0x96cb)
>     #7 0x2b7504e579cc in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::external_waiter>(tbb::detail::d1::task*, tbb::detail::r1::external_waiter&) /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/task_dispatcher.h:322
>     #8 0x2b7504e579cc in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::external_waiter>(tbb::detail::d1::task*, tbb::detail::r1::external_waiter&) /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/task_dispatcher.h:458
>     #9 0x2b7504e579cc in tbb::detail::r1::task_dispatcher::execute_and_wait(tbb::detail::d1::task*, tbb::detail::d1::wait_context&, tbb::detail::d1::task_group_context&) /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/task_dispatcher.cpp:168
>     #10 0x2b7502885d59 in edm::FinalWaitingTask::wait() (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so+0x249d59)
>     #11 0x2b75028e67b7 in edm::EventProcessor::processRuns() (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so+0x2aa7b7)
>     #12 0x2b75028c4c4d in edm::EventProcessor::runToCompletion() (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so+0x288c4d)
>     #13 0x4193a1 in tbb::detail::d1::task_arena_function<main::{lambda()#1}::operator()() const::{lambda()#1}, void>::operator()() const (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/bin/el8_amd64_gcc11/cmsRun+0x4193a1)
>     #14 0x2b7504e45846 in tbb::detail::r1::task_arena_impl::execute(tbb::detail::d1::task_arena_base&, tbb::detail::d1::delegate_base&) /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/arena.cpp:694
>     #15 0x42e3f8 in main::{lambda()#1}::operator()() const (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/bin/el8_amd64_gcc11/cmsRun+0x42e3f8)
>     #16 0x40be95 in main (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/bin/el8_amd64_gcc11/cmsRun+0x40be95)
>     #17 0x2b7505d4fd84 in __libc_start_main (/lib64/libc.so.6+0x3ad84)
>     #18 0x40c57d in _start (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/bin/el8_amd64_gcc11/cmsRun+0x40c57d)
> 
> 0x625005383900 is located 0 bytes to the right of 8192-byte region [0x625005381900,0x625005383900)
> allocated by thread T4 here:
>     #0 0x2b7501d1af37 in operator new(unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cpp:99
>     #1 0x2b7591886d33 in ap_ufixed<10, 1, (ap_q_mode)4, (ap_o_mode)0, 0>& std::vector<ap_ufixed<10, 1, (ap_q_mode)4, (ap_o_mode)0, 0>, std::allocator<ap_ufixed<10, 1, (ap_q_mode)4, (ap_o_mode)0, 0> > >::emplace_back<ap_ufixed<10, 1, (ap_q_mode)4, (ap_o_mode)0, 0> >(ap_ufixed<10, 1, (ap_q_mode)4, (ap_o_mode)0, 0>&&) [clone .isra.0] (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/libL1TriggerL1TTrackMatch.so+0x48d33)
>     #2 0x2b759186ee22 in l1tmetemu::generateCosLUT(unsigned int) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/libL1TriggerL1TTrackMatch.so+0x30e22)
>     #3 0x2b759175506e in L1TrackerEtMissEmulatorProducer::L1TrackerEtMissEmulatorProducer(edm::ParameterSet const&) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/pluginL1TrackTriggerPlugins.so+0x19606e)
>     #4 0x2b759178c8fd in edm::stream::ProducingModuleAdaptor<L1TrackerEtMissEmulatorProducer, edm::stream::EDProducerBase, edm::stream::EDProducerAdaptorBase>::setupStreamModules() (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/pluginL1TrackTriggerPlugins.so+0x1cd8fd)
>     #5 0x2b7502e12688 in edm::stream::ProducingModuleAdaptorBase<edm::stream::EDProducerBase>::doPreallocate(edm::PreallocationConfiguration const&) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so+0x7d6688)
>     #6 0x2b7502d62d16 in edm::Maker::makeModule(edm::MakeModuleParams const&, edm::signalslot::Signal<void (edm::ModuleDescription const&)>&, edm::signalslot::Signal<void (edm::ModuleDescription const&)>&) const (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so+0x726d16)
>     #7 0x2b7502a9cf09 in edm::Factory::makeModule(edm::MakeModuleParams const&, edm::ModuleTypeResolverMaker const*, edm::signalslot::Signal<void (edm::ModuleDescription const&)>&, edm::signalslot::Signal<void (edm::ModuleDescription const&)>&) const (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so+0x460f09)
>     #8 0x2b7502adfa58 in edm::ModuleRegistry::getModule(edm::MakeModuleParams const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, edm::signalslot::Signal<void (edm::ModuleDescription const&)>&, edm::signalslot::Signal<void (edm::ModuleDescription const&)>&) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so+0x4a3a58)
>     #9 0x2b7502d5572d in edm::WorkerRegistry::getWorker(edm::WorkerParams const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so+0x71972d)
>     #10 0x2b7502d5693d in edm::WorkerManager::getWorker(edm::ParameterSet&, edm::ProductRegistry&, edm::PreallocationConfiguration const*, std::shared_ptr<edm::ProcessConfiguration const>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so+0x71a93d)
>     #11 0x2b7502d57149 in edm::WorkerManager::addToUnscheduledWorkers(edm::ParameterSet&, edm::ProductRegistry&, edm::PreallocationConfiguration const*, std::shared_ptr<edm::ProcessConfiguration const>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so+0x71b149)
>     #12 0x2b7502cb5fbc in edm::StreamSchedule::StreamSchedule(std::shared_ptr<edm::TriggerResultInserter>, std::vector<edm::propagate_const<std::shared_ptr<edm::PathStatusInserter> >, std::allocator<edm::propagate_const<std::shared_ptr<edm::PathStatusInserter> > > >&, std::vector<edm::propagate_const<std::shared_ptr<edm::EndPathStatusInserter> >, std::allocator<edm::propagate_const<std::shared_ptr<edm::EndPathStatusInserter> > > >&, std::shared_ptr<edm::ModuleRegistry>, edm::ParameterSet&, edm::service::TriggerNamesService const&, edm::PreallocationConfiguration const&, edm::ProductRegistry&, edm::ExceptionToActionTable const&, std::shared_ptr<edm::ActivityRegistry>, std::shared_ptr<edm::ProcessConfiguration const>, edm::StreamID, edm::ProcessContext const*) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so+0x679fbc)
>     #13 0x2b7502c3aa77 in edm::Schedule::Schedule(edm::ParameterSet&, edm::service::TriggerNamesService const&, edm::ProductRegistry&, edm::ExceptionToActionTable const&, std::shared_ptr<edm::ActivityRegistry>, std::shared_ptr<edm::ProcessConfiguration const>, edm::PreallocationConfiguration const&, edm::ProcessContext const*, edm::ModuleTypeResolverMaker const*) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so+0x5fea77)
>     #14 0x2b7502ca8b62 in edm::ScheduleItems::initModules(edm::ParameterSet&, edm::service::TriggerNamesService const&, edm::PreallocationConfiguration const&, edm::ProcessContext const*, edm::ModuleTypeResolverMaker const*) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so+0x66cb62)
>     #15 0x2b75029eab51 in tbb::detail::d1::function_task<edm::EventProcessor::init(std::shared_ptr<edm::ProcessDesc>&, edm::ServiceToken const&, edm::serviceregistry::ServiceLegacy)::{lambda()#1}>::execute(tbb::detail::d1::execution_data&) [clone .lto_priv.0] (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so+0x3aeb51)
>     #16 0x2b7504e50303 in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&) /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/task_dispatcher.h:322
>     #17 0x2b7504e50303 in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&) /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/task_dispatcher.h:458
>     #18 0x2b7504e50303 in tbb::detail::r1::arena::process(tbb::detail::r1::thread_data&) /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/arena.cpp:137
>     #19 0x2b7504e50303 in tbb::detail::r1::market::process(rml::job&) /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/market.cpp:599
>     #20 0x2b7504e524c5 in tbb::detail::r1::rml::private_worker::run() /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/private_server.cpp:271
>     #21 0x2b7504e524c5 in tbb::detail::r1::rml::private_worker::thread_routine(void*) /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/private_server.cpp:221
> 
> Thread T4 created by T0 here:
>     #0 0x2b7501cc1716 in __interceptor_pthread_create ../../../../libsanitizer/asan/asan_interceptors.cpp:216
>     #1 0x2b7504e51b9a in tbb::detail::r1::rml::internal::thread_monitor::launch(void* (*)(void*), void*, unsigned long) /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/rml_thread_monitor.h:195
>     #2 0x2b7504e51b9a in tbb::detail::r1::rml::private_worker::wake_or_launch() /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/private_server.cpp:305
>     #3 0x2b7504e51b9a in tbb::detail::r1::rml::private_server::wake_some(int) /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/tbb-v2021.8.0/src/tbb/private_server.cpp:412
>     #4 0x2b750ae5107f  (<unknown module>)
> 
> SUMMARY: AddressSanitizer: heap-buffer-overflow (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02780/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_ASAN_X_2023-04-10-2300/lib/el8_amd64_gcc11/pluginL1TrackTriggerPlugins.so+0x18beb9) in ap_fixed_base<20, 15, true, (ap_q_mode)4, (ap_o_mode)0, 0>::RType<10, 1, false>::mult ap_fixed_base<20, 15, true, (ap_q_mode)4, (ap_o_mode)0, 0>::operator*<10, 1, false, (ap_q_mode)4, (ap_o_mode)0, 0>(ap_fixed_base<10, 1, false, (ap_q_mode)4, (ap_o_mode)0, 0> const&) const
> Shadow bytes around the buggy address:
>   0x0c4a80a686d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
>   0x0c4a80a686e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
>   0x0c4a80a686f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
>   0x0c4a80a68700: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
>   0x0c4a80a68710: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> =>0x0c4a80a68720:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
>   0x0c4a80a68730: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
>   0x0c4a80a68740: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
>   0x0c4a80a68750: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
>   0x0c4a80a68760: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
>   0x0c4a80a68770: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
> Shadow byte legend (one shadow byte represents 8 application bytes):
>   Addressable:           00
>   Partially addressable: 01 02 03 04 05 06 07 
>   Heap left redzone:       fa
>   Freed heap region:       fd
>   Stack left redzone:      f1
>   Stack mid redzone:       f2
>   Stack right redzone:     f3
>   Stack after return:      f5
>   Stack use after scope:   f8
>   Global redzone:          f9
>   Global init order:       f6
>   Poisoned by user:        f7
>   Container overflow:      fc
>   Array cookie:            ac
>   Intra object redzone:    bb
>   ASan internal:           fe
>   Left alloca redzone:     ca
>   Right alloca redzone:    cb
>   Shadow gap:              cc
> ```
> 
> https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_1_ASAN_X_2023-04-10-2300/pyRelValMatrixLogs/run/23834.999_TTbar_14TeV+2026D95PU_PMXS1S2PR/step3_TTbar_14TeV+2026D95PU_PMXS1S2PR.log#/

####Recipe to Recreate

> on lxplus or cmsdev:
> 
> ```
> $ cmssw-el8
> $ export SCRAM_ARCH=el8_amd64_gcc11
> $ scram project CMSSW_13_1_ASAN_X_2023-04-10-2300
> $ cd CMSSW_13_1_ASAN_X_2023-04-10-2300/src
> $ cmsenv
> $ git cms-addpkg L1Trigger/L1TTrackMatch
> $ USER_CXXFLAGS='-g' scram b -j8
> $ runTheMatrix.py -i all -l 23834.999 -t 4 --ibeos
> ```

**Comment by aloeliger** [comment]
As updated on the main thread, this was unable to be reproduced later. Right now, investigation does not seem possible until the error can be recreated.

**Comment by aloeliger** [comment]
This has had multiple updates since we were unable to reproduce it in april, all on the same sort of issue. I have tried to tag original developers.
