### ISSUE TITLE
Error when using L1TTurnOffGtAndGmtEmulation customisation

### ISSUE THREAD

**Issue by raggleton** [cms-l1t-offline/cmssw#232]
Adding in the customisation 

```
--customise=L1Trigger/Configuration/customiseUtils.L1TTurnOffGtAndGmtEmulation
```

into cmsDriver will cause cmsRun to fail with a bus error when using the dummy layer 1 emulator, and a `ProductNotFound` error when using the bitwise layer 1 emulator.

For example this command:

```
cmsDriver.py l1NtupleRECO -s RAW2DIGI --era=Run2_2016 --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleAODEMU --customise=L1Trigger/Configuration/customiseUtils.L1TTurnOffUnpackStage2GtGmtAndCalo --customise=L1Trigger/Configuration/customiseUtils.L1TTurnOffGtAndGmtEmulation  --conditions=auto:run2_data -n 200 --data --no_exec --no_output --filein=/store/data/Run2015D/DoubleEG/RAW-RECO/ZElectron-PromptReco-v4/000/260/627/00000/12455212-1E85-E511-8913-02163E014472.root --geometry=Extended2016,Extended2016Reco --customise=L1Trigger/Configuration/customiseReEmul.L1TEventSetupForHF1x1TPs
```

raises the following when using the dummy layer 1:

```
A fatal system signal has occurred: bus error
The following is the call stack containing the origin of the signal.

Thread 7 (Thread 0x7f9a31c3f700 (LWP 2073006)):
#0  0x0000003a1ee0f37d in waitpid () from /lib64/libpthread.so.0
#1  0x00007f9a3fb92b27 in edm::service::cmssw_stacktrace_fork() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/lib/slc6_amd64_gcc493/pluginFWCoreServicesPlugins.so
#2  0x00007f9a3fb93462 in edm::service::InitRootHandlers::stacktraceHelperThread() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/lib/slc6_amd64_gcc493/pluginFWCoreServicesPlugins.so
#3  0x00007f9a41d70ac0 in execute_native_thread_routine () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/lib64/libstdc++.so.6
#4  0x0000003a1ee07aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003a1eae893d in clone () from /lib64/libc.so.6
Thread 6 (Thread 0x7f99f2dcf700 (LWP 2073554)):
#0  0x0000003a1eae8f33 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f99f2e943e2 in XrdSys::IOEvents::PollE::Begin(XrdSysSemaphore*, int&, char const**) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/external/slc6_amd64_gcc493/lib/libXrdUtils.so.2
#2  0x00007f99f2e90c2d in XrdSys::IOEvents::BootStrap::Start(void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/external/slc6_amd64_gcc493/lib/libXrdUtils.so.2
#3  0x00007f99f2e8f447 in XrdSysThread_Xeq () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/external/slc6_amd64_gcc493/lib/libXrdUtils.so.2
#4  0x0000003a1ee07aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003a1eae893d in clone () from /lib64/libc.so.6
Thread 5 (Thread 0x7f99f23ce700 (LWP 2073555)):
#0  0x0000003a1ee0f00d in nanosleep () from /lib64/libpthread.so.0
#1  0x00007f99f2e8fbdb in XrdSysTimer::Wait(int) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/external/slc6_amd64_gcc493/lib/libXrdUtils.so.2
#2  0x00007f99f2f8df11 in XrdCl::TaskManager::RunTasks() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/external/slc6_amd64_gcc493/lib/libXrdCl.so.2
#3  0x00007f99f2f8e079 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/external/slc6_amd64_gcc493/lib/libXrdCl.so.2
#4  0x0000003a1ee07aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003a1eae893d in clone () from /lib64/libc.so.6
Thread 4 (Thread 0x7f99f19cd700 (LWP 2073556)):
#0  0x0000003a1eae5199 in syscall () from /lib64/libc.so.6
#1  0x00007f99f2fe6c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/external/slc6_amd64_gcc493/lib/libXrdCl.so.2
#2  0x00007f99f2fe6df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/external/slc6_amd64_gcc493/lib/libXrdCl.so.2
#3  0x0000003a1ee07aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x0000003a1eae893d in clone () from /lib64/libc.so.6
Thread 3 (Thread 0x7f99f0fcc700 (LWP 2073557)):
#0  0x0000003a1eae5199 in syscall () from /lib64/libc.so.6
#1  0x00007f99f2fe6c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/external/slc6_amd64_gcc493/lib/libXrdCl.so.2
  1 import FWCore.ParameterSet.Config as cms
#2  0x00007f99f2fe6df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/external/slc6_amd64_gcc493/lib/libXrdCl.so.2
#3  0x0000003a1ee07aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x0000003a1eae893d in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7f99f05cb700 (LWP 2073558)):
#0  0x0000003a1eae5199 in syscall () from /lib64/libc.so.6
#1  0x00007f99f2fe6c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/external/slc6_amd64_gcc493/lib/libXrdCl.so.2
#2  0x00007f99f2fe6df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/external/slc6_amd64_gcc493/lib/libXrdCl.so.2
#3  0x0000003a1ee07aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x0000003a1eae893d in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7f9a41a94ba0 (LWP 2072930)):
#0  0x0000003a1eadf113 in poll () from /lib64/libc.so.6
#1  0x00007f9a3fb932c4 in full_read.constprop () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/lib/slc6_amd64_gcc493/pluginFWCoreServicesPlugins.so
#2  0x00007f9a3fb9352c in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/lib/slc6_amd64_gcc493/pluginFWCoreServicesPlugins.so
#3  0x00007f9a3fb93614 in sig_dostack_then_abort () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/lib/slc6_amd64_gcc493/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00007f9a4256db27 in TIsAProxy::operator()(void const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/external/slc6_amd64_gcc493/lib/libCore.so
#6  0x00007f9a4255e32a in TClass::GetActualClass(void const*) const () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/external/slc6_amd64_gcc493/lib/libCore.so
#7  0x00007f9a42c95f57 in TTree::BranchImp(char const*, char const*, TClass*, void*, int, int) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/external/slc6_amd64_gcc493/lib/libTree.so
#8  0x00007f99eedb5a26 in L1uGTTreeProducer::L1uGTTreeProducer(edm::ParameterSet const&) () from /users/ra12451/L1JEC/TryAgain/CMSSW_8_0_2/lib/slc6_amd64_gcc493/pluginL1TriggerL1TNtuplePlugins.so
#9  0x00007f99eedba5af in edm::WorkerMaker<L1uGTTreeProducer>::makeModule(edm::ParameterSet const&) const () from /users/ra12451/L1JEC/TryAgain/CMSSW_8_0_2/lib/slc6_amd64_gcc493/pluginL1TriggerL1TNtuplePlugins.so
#10 0x00007f9a43113b26 in edm::Maker::makeModule(edm::MakeModuleParams const&, edm::signalslot::Signal<void (edm::ModuleDescription const&)>&, edm::signalslot::Signal<void (edm::ModuleDescription const&)>&) const () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#11 0x00007f9a4308bf37 in edm::Factory::makeModule(edm::MakeModuleParams const&, edm::signalslot::Signal<void (edm::ModuleDescription const&)>&, edm::signalslot::Signal<void (edm::ModuleDescription const&)>&) const () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#12 0x00007f9a4309d60d in edm::ModuleRegistry::getModule(edm::MakeModuleParams const&, std::string const&, edm::signalslot::Signal<void (edm::ModuleDescription const&)>&, edm::signalslot::Signal<void (edm::ModuleDescription const&)>&) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#13 0x00007f9a4311625c in edm::WorkerRegistry::getWorker(edm::WorkerParams const&, std::string const&) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#14 0x00007f9a4311476b in edm::WorkerManager::getWorker(edm::ParameterSet&, edm::ProductRegistry&, edm::PreallocationConfiguration const*, std::shared_ptr<edm::ProcessConfiguration const>, std::string const&) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#15 0x00007f9a430f152d in edm::StreamSchedule::fillWorkers(edm::ParameterSet&, edm::ProductRegistry&, edm::PreallocationConfiguration const*, std::shared_ptr<edm::ProcessConfiguration const>, std::string const&, bool, std::vector<edm::WorkerInPath, std::allocator<edm::WorkerInPath> >&, std::vector<std::string, std::allocator<std::string> >*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#16 0x00007f9a430f2b5e in edm::StreamSchedule::fillTrigPath(edm::ParameterSet&, edm::ProductRegistry&, edm::PreallocationConfiguration const*, std::shared_ptr<edm::ProcessConfiguration const>, int, std::string const&, std::shared_ptr<edm::HLTGlobalStatus>, std::vector<std::string, std::allocator<std::string> >*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#17 0x00007f9a430f5852 in edm::StreamSchedule::StreamSchedule(std::shared_ptr<edm::TriggerResultInserter>, std::shared_ptr<edm::ModuleRegistry>, edm::ParameterSet&, edm::service::TriggerNamesService&, edm::PreallocationConfiguration const&, edm::ProductRegistry&, edm::BranchIDListHelper&, edm::ExceptionToActionTable const&, std::shared_ptr<edm::ActivityRegistry>, std::shared_ptr<edm::ProcessConfiguration>, bool, edm::StreamID, edm::ProcessContext const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#18 0x00007f9a430d76e8 in edm::Schedule::Schedule(edm::ParameterSet&, edm::service::TriggerNamesService&, edm::ProductRegistry&, edm::BranchIDListHelper&, edm::ThinnedAssociationsHelper&, edm::ExceptionToActionTable const&, std::shared_ptr<edm::ActivityRegistry>, std::shared_ptr<edm::ProcessConfiguration>, bool, edm::PreallocationConfiguration const&, edm::ProcessContext const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#19 0x00007f9a430e5465 in edm::ScheduleItems::initSchedule(edm::ParameterSet&, bool, edm::PreallocationConfiguration const&, edm::ProcessContext const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#20 0x00007f9a4304ccef in edm::EventProcessor::init(std::shared_ptr<edm::ProcessDesc>&, edm::ServiceToken const&, edm::serviceregistry::ServiceLegacy) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#21 0x00007f9a4304e98a in edm::EventProcessor::EventProcessor(std::shared_ptr<edm::ProcessDesc>&, edm::ServiceToken const&, edm::serviceregistry::ServiceLegacy) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_2/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#22 0x000000000040cea9 in main::{lambda()#1}::operator()() const ()
#23 0x000000000040b4a6 in main ()

A fatal system signal has occurred: bus error
Bus error
```

and the following when using the bitwise layer 1:

```
----- Begin Fatal Exception 05-Apr-2016 15:59:35 BST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 260627 lumi: 293 event: 511570556
   [1] Running path 'l1ntuplesim'
   [2] Calling event method for module L1uGTTreeProducer/'l1uGTTree'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: BXVector<GlobalAlgBlk>
Looking for module label: simGtStage2Digis
Looking for productInstanceName:

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

**Comment by mulhearn** [comment]
Ah, OK, clearly that ntuple producer needs to be made more permissive (in second case)... it simply looking for GT output, which, of course, isn't there since GT emulation is turned off.  This was added to ntuple but not tested with this particular option.  But the crash is weird...
